# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

conda: 
  environment: docs/environment.yml


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

build:
   os: "ubuntu-20.04"
   tools:
     python: "mambaforge-4.10"

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install: 
     - method: pip
       path: .
