name: colvars-finder
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7
    - sphinx
    - sphinx_rtd_theme
    - setuptools
    - pytorch==1.10
    - numpy>=1.20.0
    - matplotlib
    - tqdm 
    - scikit-learn==1.0.2
    - pandas
    - pyyaml
    - pip>=21.1
    - mdanalysis==2.0.0
    - pip:
      - opencv-python
