name: colvars-finder
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7
    - sphinx<7
    - sphinx_rtd_theme
    - setuptools
    - pytorch-cpu=1.13
    - numpy>=1.20.0
    - pandas>=1.3.5
    - mdanalysis==2.0.0
    - openmm
    - openmm-plumed
    - pip>=21.1
    - tensorboardx
    - tqdm>=4.62.3
    - protobuf==3.20
    - pip:
      - scikit-learn>=1.0.2

