name: molann
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7
    - sphinx
    - sphinx_rtd_theme
    - setuptools
    - pytorch==1.10
    - numpy>=1.20.0
    - pandas
    - pyyaml
    - pip>=21.1
    - mdanalysis==2.0.0

