name: colvars-finder
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.7
    - sphinx
    - sphinx_rtd_theme
    - setuptools
    - pytorch==1.10
    - numpy>=1.20.0
    - pandas
    - mdanalysis==2.0.0
    - openmm
    - openmm-plumed
    - pip>=21.1
    - pip:
      - molann>=1.0.0

